<?php

/**
 * @file
 * Implementation of robertson library scholar customizations.
 */

/**
 * Implements hook_menu().
 */
function upei_roblib_scholar_customizations_menu() {
  return array(
    'islandora/object/%islandora_object/manage/overview/roblib_romeo' => array(
      'title' => 'Add or Update the ROMEO datastream',
      'page callback' => '_upei_roblib_scholar_customizations_add_romeo',
      'page arguments' => array(2),
      'type' => MENU_LOCAL_ACTION,
      'file' => 'includes/romeo.inc',
      'access callback' => 'upei_roblib_scholar_customizations_romeo_access',
      'access arguments' => array(2),
    ),
    'upei/roblib/autocomplete/%' => array(
      'title' => 'u1 callback',
      'page callback' => 'upei_roblib_scholar_customizations_u1_callback',
      'page arguments' => array(3),
      'type' => MENU_CALLBACK,
      'file' => 'includes/utilities.inc',
      'access arguments' => array('search islandora solr'),
    )
  );
}

/**
 * If this is a citationCModel object and has an issn show the update romeo link.
 *
 * @param \AbstractObject $object
 * @return bool
 */
function upei_roblib_scholar_customizations_romeo_access(AbstractObject $object) {
  $models = $object->models;
  if (!in_array('ir:citationCModel', $models)) {
    return FALSE;
  }
  if (empty($object['MODS'])) {
    // we can't get an issn from the mods
    return FALSE;
  }
  $mods_doc = @DOMDocument::loadXML($object['MODS']->content);
  if (empty($mods_doc)) {
    // couldn't parse the mods
    return FALSE;
  }
  $mods_xpath = new DOMXPath($mods_doc);
  $mods_xpath->registerNamespace('mods', 'http://www.loc.gov/mods/v3');
  $xpath_results = $mods_xpath->query('//mods:identifier[@type="issn" and normalize-space(text())]');
  if ($xpath_results->length > 0) {
    // take the first issn
    $issn = $xpath_results->item(0)->textContent;
  }
  if (empty($issn)) {
    return FALSE;
  }
  return TRUE;
}


/**
 * Implements hook_islandora_object_ingested
 */
function upei_roblib_scholar_customizations_islandora_object_ingested($object) {
  module_load_include('inc', 'upei_roblib_scholar_customizations', 'includes/xacml');
  module_load_include('inc', 'upei_roblib_scholar_customizations', 'includes/romeo');
  upei_roblib_scholar_customizations_add_xacml($object);
  _upei_roblib_scholar_customizations_add_romeo($object, FALSE);
}

/**
 * Implements hook_islandora_datastream_ingested
 */
function upei_roblib_scholar_customizations_islandora_datastream_ingested($object, $datastream) {
  if ($datastream->id === 'PDF') {
    module_load_include('inc', 'upei_roblib_scholar_customizations', 'includes/utilities');
    module_load_include('inc', 'upei_roblib_scholar_customizations', 'includes/romeo');
    upei_roblib_scholar_customizations_update_pdf_label($object);
    _upei_roblib_scholar_customizations_add_romeo($object, FALSE);
  }
}

/**
 * Implements hook_preprocess().
 *
 * We want to add the mads identifier[@type=u1] value to the variables array when viewing a personCModel object.
 */
function upei_roblib_scholar_customizations_preprocess_islandora_person(array &$variables) {
  $object = empty($variables['object']) ? NULL : $variables['object'];
  if (empty($object)) {
    return;
  }
  module_load_include('inc', 'upei_roblib_scholar_customizations', 'includes/utilities');
  try {
    $u1 = upei_roblib_scholar_customizations_get_u1($object, 'MADS');
  }
  catch (Exception $e) {
    watchdog_exception('UPEI Scholar Customizations', $e, 'Error retrieving u1 identifier from MADS datastream.', array(), WATCHDOG_ERROR);
  }
  $variables['u1'] = $u1;
}

/**
 * Implements hook_islandora_datastream_modified
 */
function upei_roblib_scholar_customizations_islandora_datastream_modified
(AbstractObject $object, AbstractDatastream $datastream) {
  if ($datastream->id === 'MODS' || $datastream->id === 'MADS') {
    module_load_include('inc', 'upei_roblib_scholar_customizations', 'includes/xacml');
    upei_roblib_scholar_customizations_add_xacml($object);
  }
}

/**
 * Implements hook_islandora_object_modified
 */
function upei_roblib_scholar_customizations_islandora_object_modified(AbstractObject $object) {
  module_load_include('inc', 'upei_roblib_scholar_customizations', 'includes/xacml');
  // seem to need to get a fresh copy of the object here (we were getting the old owner id if we don't work on a reloaded object).
  $object = new IslandoraFedoraObject($object->id, $object->repository);
  upei_roblib_scholar_customizations_add_xacml($object);
}

/**
 * Validate CCV research interests.
 * @param $form
 * @param $form_state
 */
function upei_roblib_scholar_customizations_validate_ccv_ri($element, $form_state) {
  /*
  if we have existing noncorfming data we will have to uncomment the below code so we can remove the bad data in the form.
  if (empty($form_state['submitted'])) {
     We are not submitting the form yet (it's possible someone just removed a tag or something and we don't want to validate yet).
    return;
  }  */
  if (empty($element['#value'])) {
    // we are not checking if this field is required.  if it has a value we validate it
    // against the taxonomy vocabulary.
    return;
  }
  // hardcoded the fieldname as it is not always included in with the element
  // for instance when using the tag element type and have multiple tags.
  $field_name = 'field_ccv_area_of_research';
  $field = field_info_field($field_name);
  $allowed = taxonomy_allowed_values($field);
  if (!in_array($element['#value'], $allowed)) {
    form_error($element, t('Invalid value %value in the %title tag list.', array('%title' => $element['#title'],
      '%value' => $element['#value'])));
  }
}

/**
 * Validate Faculty Identifiers.
 * @param $form
 * @param $form_state
 */
function upei_roblib_scholar_customizations_validate_u1($form, $form_state) {
  module_load_include('inc', 'upei_roblib_scholar_customizations', 'includes/utilities');
  _upei_roblib_scholar_customizations_fb_validate($form, $form_state,
    'u1_identifier_tabs', 'islandora\:personCModel', SOLR_MADS_FACULTY_IDENTIFIER_STRING);
}

/**
 * Validate Department identifiers.
 * @param $form
 * @param $form_state
 */
function upei_roblib_scholar_customizations_validate_u2($form, $form_state) {
  module_load_include('inc', 'upei_roblib_scholar_customizations', 'includes/utilities');
  $field_name = 'u2_identifier_tabs';
  $form_values = $form_state['values'];
  $form_element = empty($form_values[$field_name]) ? NULL : $form_values[$field_name];
  $cmodel = 'islandora\:organizationCModel';
  if (empty($form_element)) {
    $form_element = empty($form_values['affiliation']['organization_tabs']) ? NULL : $form_values['affiliation']['organization_tabs'];
    $field_name = 'affiliation';
  }
  if (empty($form_element)) {
    $field_name = 'u2_identifier_tab';
    $form_element = empty($form_values[$field_name]) ? NULL : $form_values[$field_name];
  }
  if (empty($form_element)) {
    $field_name = 'u2-identifier-tabs';
    $form_element = empty($form_values[$field_name]) ? array() : $form_values[$field_name];
  }

  _upei_roblib_scholar_customizations_fb_validate($form, $form_state,
    $field_name, $cmodel, SOLAR_MADS_DEPARTMENT_STRING, $form_element);
}


